let path = "$HOME/.vim/"
exec 'source' path . 'defaults.vim'

set showmode                      " Display the mode you're in.

set hidden                        " Handle multiple buffers better.

" Line numbers
set relativenumber 		            " Relative line numbers FTW.
set ruler                         " Show cursor position.
set statusline=[%n]\ %<%.99f\ %h%w%m%r%y\ %{exists('*CapsLockStatusline')?CapsLockStatusline():''}%=%-16(\ %l,%c-%v\ %)%P
set cursorline

" Search and replace
set incsearch                     " Highlight matches as you type.
set hlsearch                      " Highlight matches.
set gdefault                      " Always assume /g in substituions
set ignorecase                    " Case-insensitive searching.
set smartcase                     " But case-sensitive if expression contains a capital letter.

" Set linewrapping and context around cursor
set nowrap                        " Turn off line wrapping.
set scrolloff=3                   " Show 3 lines of context around the cursor.

" For use in the terminal
set title                         " Set the terminal's title
set visualbell                    " No beeping.

" Backups
set nobackup                      " Don't make a backup before overwriting a file.
set nowritebackup                 " And again.
set directory=$HOME/.vim/tmp//,.  " Keep swap files in one location

" Sort tabs out
set tabstop=2 		          
set shiftwidth=2 		        
set expandtab
set softtabstop=2

" Set my leader key
let mapleader = ","

" Save file on lost focus
autocmd FocusLost * :wa
autocmd! BufWritePost ~/.vimrc source %

" Allow to move in and out of terminals
tnoremap <C-W><Up> <C-W>k
tnoremap <C-W><Down> <C-W>j
tnoremap <C-W><Left> <C-W>h
tnoremap <C-W><Right> <C-W>l

" Set up directory navigation that makes sense 
" to my fingers
set wildmode=longest:full,full

set shellcmdflag=-lc

" Source the rest of the config
exec 'source' path . 'functions/rename_file.vim'
exec 'source' path . 'functions/delete_file.vim'
exec 'source' path . 'functions/mandate.vim'
exec 'source' path . 'functions/lint.vim'
exec 'source' path . 'plugins.vim'

" Project specific commands
noremap <Leader>cde :cd /Users/iHiD/Code/exercism/v3<CR>:source layout.vim<CR>:NERDTree<CR><C-W><Right>
