tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/cask-fonts"
tap "aws/tap"

# My products
brew "exercism"

# Essentials
brew "git"
brew "git-lfs"
brew "gh"
brew "fish"
brew "tmux"

# Tooling
brew 'ack'
brew 'tldr'
brew 'wget'
brew 'imagemagick'
brew 'dsh'

# Editors
brew 'vim'
brew 'the_silver_searcher'

# Ruby
brew "ruby-install"
brew "chruby"
brew "chruby-fish"
brew "gel"
brew "anycable-go"
brew "hivemind"

# Other Languages
brew 'nvm'
brew 'nim'

# Databases
brew 'mysql', restart_service: true
brew 'redis', restart_service: true

# Dev-dependencies
brew 'libgit2' 
brew 'cmake'
brew 'pkg-config'

# AWS
brew 'awscli@2'
brew 'terraform'
brew 'aws-sam-cli'

# Misc Dev things
brew 'zmq'

# Casks
cask "font-fira-code"
cask 'google-chrome'
cask 'spotify'
cask 'ngrok'
cask 'slack'
